### ISSUE TITLE
--include-resources not working as expected

### ISSUE THREAD

**Issue by CookieComputing** [hjacobs/kube-janitor#10]
I've been having issues trying to get `--include-resources` to work as expected.

I tried two variants of this spec but didn't get anything to work:
```
spec:
      containers:
      - args:
        - --debug
        - --interval=20
        - --rules-file=/config/rules.yaml
        - --include-resources=deployment
```

```
spec:
      containers:
      - args:
        - --debug
        - --interval=20
        - --rules-file=/config/rules.yaml
        - --include-resources=deployment
        - --include-namespaces=default
```

I ran `kubectl run temp-nginx --image=nginx` and annotated it with `kubectl annotate deploy temp-nginx janitor/ttl=5s`, but the deployment doesn't disappear after a loop run. Any ideas on what to do?
