### ISSUE TITLE
Deleting CRDS like EtcdCluster is not working

### ISSUE THREAD

**Issue by christianhuening** [hjacobs/kube-janitor#46]
I am trying to delete CRDs like `EtcdCluster` via Janitor. Specified like so:
```yaml
rulesFile:
    rules:
      - id: namespace-cleanup
        resources:
        - deployments
        - services
        - etcdcluster
        jmespath: "!(spec.template.metadata.labels.janitorIgnore)"
        ttl: 12h
```

it does not delete the etcdcluster resource. This resource is introduced by the Etcd Operator from coreOS. Do I have to specify the CRDs somehow special?
