### ISSUE TITLE
Remove unmounted/unused PVCs

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-janitor#62]
Kubernetes Janitor should allow deleting PersistentVolumeClaims which are no longer mounted or referenced, e.g. because the StatefulSet was deleted.

PVCs are not automatically deleted and it's easy to forget them. From https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/:
> Deleting and/or scaling a StatefulSet down will not delete the volumes associated with the StatefulSet. This is done to ensure data safety, which is generally more valuable than an automatic purge of all related StatefulSet resources.

Idea: add additional context properties which can be used in the rule `jmespath`.

**Comment by hjacobs** [comment]
To delete all unused PVCs, use a rules file (`--rules-file` option) with the following contents:

```yaml
rules:
- id: remove-unused-pvcs
  resources:
  - persistentvolumeclaims
  jmespath: "_context.pvc_is_not_mounted && _context.pvc_is_not_referenced"
  ttl: 24h
```
