### ISSUE TITLE
Not iterating over all namespaces

### ISSUE THREAD

**Issue by ghostsquad** [hjacobs/kube-janitor#74]
It looks like this is not iterating over all namespaces. 

I see this

```
[kube-janitor-7cc797f987-5pgjz] 2020-05-04 00:26:44,482 INFO: Clean up run completed: resources-processed=3012
```

and looking over the previous logs, it just looked at resources in the namespace it's deployed in (`kube-system`)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tunein.com/component: kube-janitor
    tunein.com/deploy-environment: nonprod
    tunein.com/managed-by: make
    tunein.com/project: eks-cluster-ops
    tunein.com/team: devops
    tunein.com/version: 20.4.0
  labels:
    app: kube-janitor
    version: 20.4.0
  name: kube-janitor
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-janitor
  template:
    metadata:
      labels:
        app: kube-janitor
        version: 20.4.0
    spec:
      containers:
      - args:
        - --dry-run
        - --debug
        - --interval=60
        image: hjacobs/kube-janitor:20.4.0
        name: janitor
        resources:
          limits:
            cpu: 500m
            memory: 110Mi
          requests:
            cpu: 5m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      serviceAccountName: kube-janitor
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kube-janitor
  name: kube-janitor
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - delete
```

Not sure why
